/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Reporter.Reporter;
import Business.Reporter.ReporterDirectory;
import Business.RescueTeam.RescueTeam;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class ReporterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReporterJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory userAccountList;
   
    public ReporterJPanel(JPanel parentContainerPanel,EcoSystem ecosystem) {
        initComponents();
        initListners();
        this.userProcessContainer=parentContainerPanel;
        this.ecosystem=ecosystem;
         populateTable();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        createUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        createPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createAddress = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        createPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 708));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 490, 165));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        createUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserNameActionPerformed(evt);
            }
        });
        add(createUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 259, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        add(createPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 259, -1));

        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        add(createName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 259, -1));

        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        add(createAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 259, -1));

        btnCreateCustomer.setText("Create");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });
        add(btnCreateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 82, -1));

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 73, -1));

        jLabel6.setText("Phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        add(createPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 259, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportersys.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserNameActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:

        if( createUserName.getText().isEmpty()||createPassword.getText().isEmpty()|| createName.getText().isEmpty() || createAddress.getText().isEmpty() || createPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }

        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(createUserName.getText())){
            Reporter Reporter = new Reporter(createUserName.getText(), createPassword.getText(), createName.getText(), createAddress.getText(), createPhone.getText());
            ecosystem.getUserAccountDirectory().addUserAccount(Reporter);
            ecosystem.getReporterDirectory().addReporter(Reporter);
            populateTable();
            createUserName.setText("");
            createPassword.setText("");
            createName.setText("");
            createAddress.setText("");
            createPhone.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Username " + createUserName.getText() + " already exists !!!, Please try a new one");
        }
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        System.out.println("Update");

        int selectedRow = tblCustomer.getSelectedRow();
        if (selectedRow >= 0) {
            System.out.println("xyz" + selectedRow);
            System.out.println("2");
            Reporter Reporter = (Reporter) tblCustomer.getValueAt(selectedRow, 0);
            System.out.println("item : " + Reporter);
            Reporter.setUsername(createUserName.getText());
            Reporter.setPassword(createPassword.getText());
            Reporter.setName(createName.getText());
            Reporter.setPhone(createPhone.getText());
            Reporter.setAddress(createAddress.getText());
            populateTable();
            createUserName.setText("");
            createPassword.setText("");
            createName.setText("");
            createPhone.setText("");
            createAddress.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblCustomer.getSelectedRow();

        if (selectedRow >= 0) {
            Reporter customer = (Reporter) tblCustomer.getValueAt(selectedRow, 0);
            ReporterDirectory customerDirectory = ecosystem.getReporterDirectory();
            customerDirectory.removeReporter(customer);
            JOptionPane.showMessageDialog(null, "Customer   "  + createUserName.getText() + " deleted");
            populateTable();
            createName.setText("");
            createPhone.setText("");
            createUserName.setText("");
            createPassword.setText("");
            createAddress.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
     private void populateTable() {
        ReporterDirectory ReporterDirectory = ecosystem.getReporterDirectory();
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();

        model.setRowCount(0);
        for (Reporter Reporter : ReporterDirectory.getReporterList()) {
                    Object[] row = new Object[5];
                    row[0] = Reporter;
                    row[1] = Reporter.getAddress();
                    row[2] = Reporter.getPhone();
                    row[3] = Reporter.getUsername();
                    row[4] = Reporter.getPassword();

                    model.addRow(row);
                
            }
        
    }
       private void initListners() {
       tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           int selectedRow = tblCustomer.getSelectedRow();
             if (selectedRow >= 0) {
                  Reporter  Reporter  = (Reporter) tblCustomer.getValueAt(selectedRow, 0);
                 if(Reporter!=null){
                     display(Reporter);
                 }
             }
        }
    });
    }
     

    private void display(Reporter Reporter) {
        System.out.println("display");
        createUserName.setText(Reporter.getUsername());
        createPassword.setText(Reporter.getPassword());
        createName.setText(Reporter.getName());
        createPhone.setText(Reporter.getPhone());
        createAddress.setText(Reporter.getAddress());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JTextField createAddress;
    private javax.swing.JTextField createName;
    private javax.swing.JTextField createPassword;
    private javax.swing.JTextField createPhone;
    private javax.swing.JTextField createUserName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables
}
