/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VerificationAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
//import Business.Location.LocationPoint;
import Business.Network.Network;
import Business.Organization.RescueVerifyingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.WorkQueue.RescueAdminReportRequest;
import Business.WorkQueue.VolunteerReportRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class VerificationAdminManageRequestsJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Organization organization;
    Network network;
   
    private UserAccount account;
    /**
     * Creates new form IncidentUnitManageScene
     */
    public VerificationAdminManageRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, Organization organization, Network network,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.network = network;
        this.account = account;
        sceneTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateSceneTable();
    }
    
    private void populateSceneTable(){
        sceneTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) sceneTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            
            if (wr instanceof VolunteerReportRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = wr;
                row[1] = ((VolunteerReportRequest) wr).getSceneName();
                row[2] = ((VolunteerReportRequest) wr).getSceneZipcode();
               
                row[3] = ((VolunteerReportRequest) wr).getNoOfVictims();
               
                row[4] = ((VolunteerReportRequest) wr).getStatus();
                row[5] = ((VolunteerReportRequest) wr).getRequestDate();
                row[6] = ((VolunteerReportRequest) wr).getMessage();
                model.addRow(row);
            }
        }
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sceneTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sceneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sceneZipCode = new javax.swing.JTextField();
        noOfVictims = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createSceneBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sceneTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Scene #", "Scene Name", "Zip Code", "# of Victims", "Status", "Created Date", "Additional Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sceneTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        sceneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sceneTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sceneTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 48, 1010, 146));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Scene Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 211, -1, -1));

        sceneName.setEditable(false);
        sceneName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneName.setForeground(new java.awt.Color(25, 56, 82));
        sceneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceneNameActionPerformed(evt);
            }
        });
        add(sceneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 188, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setText("Zip Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 254, -1, -1));

        sceneZipCode.setEditable(false);
        sceneZipCode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneZipCode.setForeground(new java.awt.Color(25, 56, 82));
        add(sceneZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 250, 190, -1));

        noOfVictims.setEditable(false);
        noOfVictims.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        noOfVictims.setForeground(new java.awt.Color(25, 56, 82));
        add(noOfVictims, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 292, 188, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("No of Dogs");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 297, -1, -1));

        createSceneBtn.setBackground(new java.awt.Color(255, 255, 255));
        createSceneBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createSceneBtn.setForeground(new java.awt.Color(25, 56, 82));
        createSceneBtn.setText("Approve");
        createSceneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSceneBtnActionPerformed(evt);
            }
        });
        add(createSceneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 713, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setText("Report Image");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 56, 82));
        jButton1.setText("Reject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 713, -1, -1));

        jLabel7.setText("Picture will display here");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setPreferredSize(new java.awt.Dimension(460, 280));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 361, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 56, 82));
        jLabel8.setText("MANAGE REQUEST");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 8, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sceneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sceneNameActionPerformed

    private void createSceneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSceneBtnActionPerformed
        
        int selectedRow = sceneTable.getSelectedRow();        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Report", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Assigned Verifying Admin")){
            String msg = JOptionPane.showInputDialog("Additional Message");
        
            selectedWorkReq.setStatus("Forwarded to Volunteer");
            selectedWorkReq.setMessage(msg);

            RescueAdminReportRequest sceneReq = new RescueAdminReportRequest();
            sceneReq.setSceneName(sceneName.getText());
            sceneReq.setSceneZipcode(sceneZipCode.getText());
            sceneReq.setNoOfVictims(Integer.parseInt(noOfVictims.getText()));
          
            sceneReq.setStatus("Requested");  
            sceneReq.setSender(account);
          
            sceneReq.setMessage("Waiting for Volunteer head to approve request");

            account.getWorkQueue().getWorkRequestList().add(sceneReq);

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof RescueVerifyingOrganization) {
                         o.getWorkQueue().getWorkRequestList().add(sceneReq);
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Request is Accepted successfully");
            populateSceneTable();
        }else if(selectedWorkReq.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Request is already Rejected", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Cancelled")) {
            JOptionPane.showMessageDialog(null, "Request has been cancelled by the user", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "Request is already Accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_createSceneBtnActionPerformed
    VolunteerReportRequest selectedWorkReq;
    private void sceneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sceneTableMouseClicked
        //int selectedReq = sceneTable.rowAtPoint(evt.getPoint());
        
        int selectedReq = sceneTable.getSelectedRow();
        selectedWorkReq = (VolunteerReportRequest)sceneTable.getValueAt(selectedReq, 0);
        sceneName.setText(selectedWorkReq.getSceneName());
        sceneZipCode.setText(selectedWorkReq.getSceneZipcode());
        noOfVictims.setText(selectedWorkReq.getNoOfVictims()+"");
    
        sceneName.setText(selectedWorkReq.getSceneName());
       
        System.out.println("/********/////");
        displayDImage(selectedWorkReq.getImagePath());
        
        
    }//GEN-LAST:event_sceneTableMouseClicked
    
    public void displayDImage(String bb) {
        String imgPath = bb;
        ImageIcon imgIcon = new ImageIcon(imgPath);  
        Image imgFit = imgIcon.getImage().getScaledInstance(460, 280, Image.SCALE_SMOOTH);
        jLabel7.setText("");
        jLabel7.setIcon(new ImageIcon(imgFit));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int selectedRow = sceneTable.getSelectedRow();        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Report", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Assigned Verifying Admin")){
            String msg = JOptionPane.showInputDialog("Additional Message");
            selectedWorkReq.setStatus("Rejected");
            selectedWorkReq.setMessage(msg);
            populateSceneTable();
            JOptionPane.showMessageDialog(null, "Request is Rejected successfully");
        }else if(selectedWorkReq.getStatus().equals("Forwarded to Volunteer Team")){
            JOptionPane.showMessageDialog(null, "Request is already Accepted");
        }else if(selectedWorkReq.getStatus().equals("Cancelled")) {
            JOptionPane.showMessageDialog(null, "Request has been cancelled by the user", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(selectedWorkReq.getStatus().equals("Forwarded to Volunteer Team")) {
            JOptionPane.showMessageDialog(null, "Request has already been accepted and processed", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "Request is already Rejected");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSceneBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVictims;
    private javax.swing.JTextField sceneName;
    private javax.swing.JTable sceneTable;
    private javax.swing.JTextField sceneZipCode;
    // End of variables declaration//GEN-END:variables
}
