/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReportingUnitPersonal;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.RescueManagementUnit;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.Utils.Validation;
import Business.WorkQueue.RescueAdminReportRequest;
import Business.WorkQueue.VolunteerReportRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class IndividualAdminManageReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndividualAdminManageReportJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Organization organization;
    Network network;
    UserAccount account;
   
    private String imagePath;

    public IndividualAdminManageReportJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, Organization organization, Network network, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.network = network;
        this.account = account;
         tblScene.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateSceneTable();
    }

    private void populateSceneTable() {
        tblScene.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) tblScene.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {

            if (wr instanceof VolunteerReportRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = wr;
                row[1] = ((VolunteerReportRequest) wr).getSceneName();
                row[2] = ((VolunteerReportRequest) wr).getSceneZipcode();
                row[3] = ((VolunteerReportRequest) wr).getNoOfVictims();
                row[4] = ((VolunteerReportRequest) wr).getStatus();
                row[5] = ((VolunteerReportRequest) wr).getRequestDate();
                row[6] = ((VolunteerReportRequest) wr).getMessage();
               
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblScene = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sceneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sceneZipCode = new javax.swing.JTextField();
        noOfVictims = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createSceneBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        createAddPic = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        imageJPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblScene.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblScene.setForeground(new java.awt.Color(25, 56, 82));
        tblScene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Scene #", "Scene Name", "Zip Code", "# of Victims", "Status", "Created Date", "Additional Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblScene);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1020, 146));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MANAGE INDVIDUAL SCENE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 849, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Report Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 204, -1, -1));

        sceneName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneName.setForeground(new java.awt.Color(25, 56, 82));
        sceneName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sceneNameFocusLost(evt);
            }
        });
        sceneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceneNameActionPerformed(evt);
            }
        });
        add(sceneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 199, 188, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setText("Zip Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 248, -1, -1));

        sceneZipCode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneZipCode.setForeground(new java.awt.Color(25, 56, 82));
        add(sceneZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 243, 188, -1));

        noOfVictims.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        noOfVictims.setForeground(new java.awt.Color(25, 56, 82));
        noOfVictims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noOfVictimsKeyPressed(evt);
            }
        });
        add(noOfVictims, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 287, 188, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("Number of Dogs");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 292, -1, -1));

        createSceneBtn.setBackground(new java.awt.Color(255, 255, 255));
        createSceneBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createSceneBtn.setForeground(new java.awt.Color(25, 56, 82));
        createSceneBtn.setText("Create Report");
        createSceneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSceneBtnActionPerformed(evt);
            }
        });
        add(createSceneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 56, 82));
        jLabel7.setText("Add Picture");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        createAddPic.setBackground(new java.awt.Color(255, 255, 255));
        createAddPic.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        createAddPic.setForeground(new java.awt.Color(25, 56, 82));
        createAddPic.setText("Upload Picture");
        createAddPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAddPicActionPerformed(evt);
            }
        });
        add(createAddPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, 40));

        fileNameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fileNameLabel.setForeground(new java.awt.Color(25, 56, 82));
        fileNameLabel.setText("<Value>");
        add(fileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 430, -1));

        imageJPanel.setBackground(new java.awt.Color(153, 153, 153));
        imageJPanel.setLayout(new java.awt.BorderLayout());
        add(imageJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 460, 280));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 56, 82));
        jButton1.setText("Cancel Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sceneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sceneNameActionPerformed

    private void createSceneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSceneBtnActionPerformed
        int zipCode, victimCount, loss;
        if("".equals(sceneName.getText())){
            JOptionPane.showMessageDialog(null, "Report Name is mandatory");
        }else if("".equals(sceneZipCode.getText())){
            JOptionPane.showMessageDialog(null, "Report Zip Code is mandatory");
        }else if(!Pattern.compile("^[0-9]{6}(?:-[0-9]{5})?$").matcher(sceneZipCode.getText()).matches()) {
            JOptionPane.showMessageDialog(null, "Report Zip Code is not in the correct format");
        }else if("".equals(noOfVictims.getText())){
            JOptionPane.showMessageDialog(null, "No of Dogs is mandatory");
        }
        
        else if("".equals(imagePath) || null == imagePath){
            JOptionPane.showMessageDialog(null, "Uploading an image is mandatory");
        }else {
            try {
                zipCode = Integer.parseInt(sceneZipCode.getText());
                victimCount = Integer.parseInt(noOfVictims.getText());
                
            String msg = JOptionPane.showInputDialog("Additional Message");
            VolunteerReportRequest sceneReq = new VolunteerReportRequest();
            sceneReq.setSceneName(sceneName.getText());
            sceneReq.setSceneZipcode(sceneZipCode.getText());
            sceneReq.setNoOfVictims(Integer.parseInt(noOfVictims.getText()));
        
            sceneReq.setRequestDate(new Date());
            sceneReq.setMessage(msg);
            sceneReq.setStatus("Requested");
            sceneReq.setImagePath(imagePath);
            sceneReq.setSender(account);
            organization.getWorkQueue().getWorkRequestList().add(sceneReq);
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(e instanceof RescueManagementUnit) {
                    e.getWorkQueue().getWorkRequestList().add(sceneReq);
                }
            }
            JOptionPane.showMessageDialog(null, "Report Created Successfully");
            populateSceneTable();
            resetFields();
            }catch(NumberFormatException exception){
                JOptionPane.showMessageDialog(null, "ZipCode and No of Dogs need to be in integer!");
            }
        }
    }//GEN-LAST:event_createSceneBtnActionPerformed
    
    public void resetFields() {
        sceneName.setText("");
        sceneZipCode.setText("");
        noOfVictims.setText("");
        fileNameLabel.setText("");
        imgLabel.setIcon(null);
        //imageJPanel.remove(imgLabel);
        imgLabel.revalidate();
    }
    
    private void createAddPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAddPicActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            fileNameLabel.setText(imagePath);
            displayImage(imagePath);
            JOptionPane.showMessageDialog(null, "Picture Uploaded Successfully");

        }
    }//GEN-LAST:event_createAddPicActionPerformed
    
    private void sceneNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sceneNameFocusLost
        //JOptionPane.showMessageDialog(null, "fsff");
    }//GEN-LAST:event_sceneNameFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblScene.getSelectedRow();        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Report", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            VolunteerReportRequest selectedWorkReq = (VolunteerReportRequest)tblScene.getValueAt(selectedRow, 0);
            if(selectedWorkReq.getStatus().equals("Requested")) {
                String msg = JOptionPane.showInputDialog("Additional Message");
                selectedWorkReq.setStatus("Cancelled");
                selectedWorkReq.setMessage(msg);
                JOptionPane.showMessageDialog(null, "Report Request has been cancelled");
            }else if(selectedWorkReq.getStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Request has already been rejected");
            }else {
                JOptionPane.showMessageDialog(null, "Request is already processed and cannot be cancelled.");
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noOfVictimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noOfVictimsKeyPressed
        Validation.integerValidator(evt, noOfVictims);
    }//GEN-LAST:event_noOfVictimsKeyPressed

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(460, 280, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    JLabel imgLabel;
    public void displayImage(String imgPath) {
        System.out.println("FILE PATH = " + imgPath);
        imageJPanel.removeAll();
        imgLabel = new JLabel(ResizeImage(imgPath));
        imageJPanel.add(imgLabel);
        imageJPanel.invalidate();
    }

    public void displayImage(RescueAdminReportRequest sceneReq) {
        System.out.println("FILE PATH = " + sceneReq.getImagePath());
        displayImage(sceneReq.getImagePath());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAddPic;
    private javax.swing.JButton createSceneBtn;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JPanel imageJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfVictims;
    private javax.swing.JTextField sceneName;
    private javax.swing.JTextField sceneZipCode;
    private javax.swing.JTable tblScene;
    // End of variables declaration//GEN-END:variables
}
