/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.HelpCenter.Services;
import Business.HelpCenter.HelpCenter;
import Business.HelpCenter.HelpCenterDirectory;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivibhatt
 */
public class ManageHelpCenterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHelpCenterJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory userAccountList;

    public ManageHelpCenterJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        initListners();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantAdmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createRestaurantName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        createPassword = new javax.swing.JTextField();
        createUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        restaurantAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        restaurantPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRestaurantAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurantAdmin);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 410, 165));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setText("Help Center Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 112, -1));
        add(createRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 259, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 82, -1));

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 73, -1));
        add(createPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 259, -1));

        createUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserNameActionPerformed(evt);
            }
        });
        add(createUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 259, -1));

        jLabel4.setText("Help Center Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        add(restaurantAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 259, -1));

        jLabel6.setText("Help Center Phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 112, -1));
        add(restaurantPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 259, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rescueteam.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (createUserName.getText().isEmpty() || createPassword.getText().isEmpty() || createRestaurantName.getText().isEmpty() || restaurantAddress.getText().isEmpty()
              || restaurantPhone.getText().isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }

        if (ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(createUserName.getText())) {
            HelpCenter restaurant = new HelpCenter(createUserName.getText(),
                    createPassword.getText(), createRestaurantName.getText(),
                    restaurantAddress.getText(),restaurantPhone.getText());
            ecosystem.getUserAccountDirectory().addUserAccount(restaurant);
            ecosystem.getRestaurantDirectory().addRestaurant(restaurant);
            populateTable();
            createUserName.setText("");
            createPassword.setText("");
            createRestaurantName.setText("");
            restaurantAddress.setText("");
            restaurantPhone.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Username " + createUserName.getText() + " already exists !!!, Please try a new one");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        System.out.println("Shivi Update");

        int selectedRow = tblRestaurantAdmin.getSelectedRow();
        if (selectedRow >= 0) {
            System.out.println("xyz" + selectedRow);
            System.out.println("Shivi 2");
            HelpCenter restaurant = (HelpCenter) tblRestaurantAdmin.getValueAt(selectedRow, 0);
            System.out.println("item : " + restaurant);
            restaurant.setUsername(createUserName.getText());
            restaurant.setPassword(createPassword.getText());
            restaurant.setName(createRestaurantName.getText());
            restaurant.setAddress(restaurantAddress.getText());
            restaurant.setPhone(restaurantPhone.getText());
            populateTable();
            createUserName.setText("");
            createPassword.setText("");
            createRestaurantName.setText("");
            restaurantAddress.setText("");
            restaurantPhone.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
           int selectedRow = tblRestaurantAdmin.getSelectedRow();

        if (selectedRow >= 0) {
            HelpCenter restaurant = (HelpCenter) tblRestaurantAdmin.getValueAt(selectedRow, 0);
            HelpCenterDirectory restaurantDirectory = ecosystem.getRestaurantDirectory();
            restaurantDirectory.removeRestaurant(restaurant);
            JOptionPane.showMessageDialog(null, "Restaurant admin "  + createUserName.getText() + " deleted");
            populateTable();
            createUserName.setText("");
            createPassword.setText("");
            createRestaurantName.setText("");
            restaurantAddress.setText("");
            restaurantPhone.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
           
      
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void populateTable() {
        HelpCenterDirectory restaurantDirectory = ecosystem.getRestaurantDirectory();
        DefaultTableModel model = (DefaultTableModel) tblRestaurantAdmin.getModel();
        model.setRowCount(0);
        for (HelpCenter restaurant : restaurantDirectory.getRestaurantList()) {
            Object[] row = new Object[3];
            row[0] = restaurant;
            row[1] = restaurant.getUsername();
            row[2] = restaurant.getPassword();
            model.addRow(row);
        }
    }

   
    private void initListners() {
       tblRestaurantAdmin.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           int selectedRow = tblRestaurantAdmin.getSelectedRow();
             if (selectedRow >= 0) {
                  HelpCenter  restaurant  = (HelpCenter) tblRestaurantAdmin.getValueAt(selectedRow, 0);
                 if(restaurant!=null){
                     display(restaurant);
                 }
             }
        }
    });
    }

    private void display(HelpCenter restaurant) {
        System.out.println("Shivi display");
        createUserName.setText(restaurant.getUsername());
        createPassword.setText(restaurant.getPassword());
        createRestaurantName.setText(restaurant.getName());
        restaurantAddress.setText(restaurant.getAddress());
        restaurantPhone.setText(restaurant.getPhone());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JTextField createPassword;
    private javax.swing.JTextField createRestaurantName;
    private javax.swing.JTextField createUserName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField restaurantAddress;
    private javax.swing.JTextField restaurantPhone;
    private javax.swing.JTable tblRestaurantAdmin;
    // End of variables declaration//GEN-END:variables
}
