/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerManagementWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ReportingUnit;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.HeaderColors;
import Business.Utils.Validation;
import Business.WorkQueue.RescueUnitRequest;
import Business.WorkQueue.RescueAdminReportRequest;
import Business.WorkQueue.UserRegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.OrgAvailable.AvailableOrganizationJPanel;
import userinterface.UserRegistration.UserRegistrationJPanel;

public class ReportVolunteerManagerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Network network;
    EcoSystem business;
    Organization organization;
    RescueAdminReportRequest selectedWorkReq;
    
    public ReportVolunteerManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        selectedWorkReq = null;
        statusTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        sceneTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        populateSceneTable();
        populateStatusTable();
    }

    private void populateStatusTable() {
       
        statusTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) statusTable.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {            
            if(wr instanceof RescueUnitRequest && null != selectedWorkReq) {
                
                if(selectedWorkReq.getSceneId().equals(((RescueUnitRequest) wr).getSceneId())) {
                    Object[] row = new Object[model.getColumnCount()];                
                    row[0] = ((RescueUnitRequest) wr);
                    row[1] = ((RescueUnitRequest) wr).getStatus();
                    row[2] = ((RescueUnitRequest) wr).getRecieverOrganization().getName();
                    row[3] = ((RescueUnitRequest) wr).getRequestDate();
                    row[4] = ((RescueUnitRequest) wr).getSender().getEmployee().getName();
                    row[5] = ((RescueUnitRequest) wr).getMessage();
                    row[6] = ((RescueUnitRequest) wr).getSceneId();
                    row[7] = ((RescueUnitRequest) wr).getRecieverNetwork().getName();
                    model.addRow(row);
                }
            }            
        }
    
    }

    private void populateSceneTable() {
        sceneTable.getTableHeader().setDefaultRenderer(new HeaderColors());
        DefaultTableModel model = (DefaultTableModel) sceneTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            if(wr instanceof RescueAdminReportRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = ((RescueAdminReportRequest) wr);
                row[1] = ((RescueAdminReportRequest) wr).getSceneName();
                row[2] = ((RescueAdminReportRequest) wr).getNoOfVictims();
                row[3] = ((RescueAdminReportRequest) wr).getSceneZipcode();
                row[4] = ((RescueAdminReportRequest) wr).getSender();
                row[5] = ((RescueAdminReportRequest) wr).getStatus();
                row[6] = ((RescueAdminReportRequest) wr).getRequestDate();
                row[7] = ((RescueAdminReportRequest) wr).getMessage();
                model.addRow(row);
            }
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sceneTable = new javax.swing.JTable();
        nearestOrgSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        cancelReqBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1338, 840));
        setPreferredSize(new java.awt.Dimension(1338, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sceneTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sceneTable.setForeground(new java.awt.Color(25, 56, 82));
        sceneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Report Id", "Report  Name", "Dogs", "ZipCode", "Sender", "Status", "Created Date", "Additional Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sceneTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        sceneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sceneTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sceneTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1250, 101));

        nearestOrgSearch.setBackground(new java.awt.Color(255, 255, 255));
        nearestOrgSearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nearestOrgSearch.setForeground(new java.awt.Color(25, 56, 82));
        nearestOrgSearch.setText("Search for Available Organization");
        nearestOrgSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearestOrgSearchActionPerformed(evt);
            }
        });
        add(nearestOrgSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        statusTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Requests", "Status", "Reciever Org", "Request Date", "Sender", "Message", "Report Id", "Reciever Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statusTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane2.setViewportView(statusTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1250, 129));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 56, 82));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(25, 56, 82));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(25, 56, 82));
        jButton3.setText("Mark Resolved");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        processBtn.setBackground(new java.awt.Color(255, 255, 255));
        processBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        processBtn.setForeground(new java.awt.Color(25, 56, 82));
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        cancelReqBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelReqBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cancelReqBtn.setForeground(new java.awt.Color(25, 56, 82));
        cancelReqBtn.setText("Cancel Request");
        cancelReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReqBtnActionPerformed(evt);
            }
        });
        add(cancelReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 560, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REPORT LIST");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 780, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 56, 82));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" REQUEST LIST");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 380, 850, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nearestOrgSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearestOrgSearchActionPerformed
        // TODO add your handling code here:
        int selectedRow = sceneTable.getSelectedRow();        
        RescueAdminReportRequest selectedScene = null;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to view available organizations", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedScene = (RescueAdminReportRequest) sceneTable.getValueAt(selectedRow, 0);
           
            if(selectedScene.getStatus().equals("Resolved")) {
                JOptionPane.showMessageDialog(null, "Report is already Resolved");
            }else if(selectedScene.getStatus().equals("Volunteer Manager Assigned")) {
                JOptionPane.showMessageDialog(null, "Please process the Report before sending requests to organizations");
            }else {
                AvailableOrganizationJPanel ramop = new AvailableOrganizationJPanel(userProcessContainer, account, organization, selectedScene, enterprise, network, business);
                userProcessContainer.add("Available_ORG", ramop);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_nearestOrgSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateSceneTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populateStatusTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = sceneTable.getSelectedRow();        
        RescueAdminReportRequest selectedScene = null;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Report", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            boolean isReqCompleted = true;
            for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {            
                if(wr instanceof RescueUnitRequest && null != selectedWorkReq) {
                    if(selectedWorkReq.getSceneId().equals(((RescueUnitRequest) wr).getSceneId())) {
                        if(!((RescueUnitRequest)wr).getStatus().equals("Completed") && !((RescueUnitRequest)wr).getStatus().equals("Cancelled") && !((RescueUnitRequest)wr).getStatus().equals("Rejected")) {
                            isReqCompleted = false;
                            break;
                        }
                    }
                }            
            }
            
            if(isReqCompleted) {
                RescueAdminReportRequest sScene = (RescueAdminReportRequest) sceneTable.getValueAt(selectedRow, 0);
                if(sScene.getStatus().equals("Resolved")) {
                    JOptionPane.showMessageDialog(null, "Report is already Resolved");
                }else if(sScene.getStatus().equals("Volunteer Manager Assigned")) {
                    JOptionPane.showMessageDialog(null, "Please process the Report before marking resolved");
                }else {
                    String msg = JOptionPane.showInputDialog("Additional Message");                    
                    sScene.setStatus("Resolved");
                    sScene.setMessage(msg);
                }
                
            }else {
                JOptionPane.showMessageDialog(null, "There are pending requests for this Report. Please wait for them to be completed before marking resolved.");
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sceneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sceneTableMouseClicked
        
        int selectedReq = sceneTable.getSelectedRow();
        if(selectedReq >= 0){
        selectedWorkReq = (RescueAdminReportRequest)sceneTable.getValueAt(selectedReq, 0);
        populateStatusTable();
        }
    }//GEN-LAST:event_sceneTableMouseClicked

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int selectedRow = sceneTable.getSelectedRow();        
        RescueAdminReportRequest selectedScene = null;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the Report", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedScene = (RescueAdminReportRequest) sceneTable.getValueAt(selectedRow, 0);
            if(selectedScene.getStatus().equals("Processing")) {
                JOptionPane.showMessageDialog(null, "report is already in Processing state");
            }else if(selectedScene.getStatus().equals("Resolved")) {
                JOptionPane.showMessageDialog(null, "report is already Resolved");
            }else {
                String msg = JOptionPane.showInputDialog("Additional Message");
                selectedScene.setStatus("Processing");
                selectedScene.setMessage(msg);
                populateSceneTable();
            }
            
        }
    }//GEN-LAST:event_processBtnActionPerformed

    private void cancelReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReqBtnActionPerformed
        int selectedRow = statusTable.getSelectedRow();        
        RescueUnitRequest selectedReq = null;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedReq = (RescueUnitRequest) statusTable.getValueAt(selectedRow, 0);
            if(selectedReq.getStatus().equals("Processing") || selectedReq.getStatus().equals("Completed")) {
                JOptionPane.showMessageDialog(null, "This request canot be cancelled");
            }else if(selectedReq.getStatus().equals("Cancelled")) {
                JOptionPane.showMessageDialog(null, "This request is already cancelled");
            }else if(selectedReq.getStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "This request has already been rejected");
            } else {
                String msg = JOptionPane.showInputDialog("Additional Message");
                selectedReq.setStatus("Cancelled");
                selectedReq.setMessage(msg);
                JOptionPane.showMessageDialog(null, "This request has been cancelled");
                populateStatusTable();
            }            
        }
    }//GEN-LAST:event_cancelReqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelReqBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nearestOrgSearch;
    private javax.swing.JButton processBtn;
    private javax.swing.JTable sceneTable;
    private javax.swing.JTable statusTable;
    // End of variables declaration//GEN-END:variables
}
